import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import { Header } from '../components/header';
import NavBar from '../components/navbar';

const geistSans = localFont({
	src: './fonts/GeistVF.woff',
	variable: '--font-geist-sans',
	weight: '100 900'
});
const geistMono = localFont({
	src: './fonts/GeistMonoVF.woff',
	variable: '--font-geist-mono',
	weight: '100 900'
});

export const metadata: Metadata = {
	title: '::: SGV - Sistema de Gerenciamento de Vendas :::',
	description: 'Generated by create next app'
};

export default function RootLayout({
	children
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="pt-br" suppressHydrationWarning={true}>
			<body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
				<NavBar />

				<div className="flex w-full bg-lime-300 h-1/3 ">
					<img src="/images/home.png" alt="imagem home" className="m-auto w-full h-96" />
					
				</div>

				{children}
			</body>
		</html>
	);
}
